=== ffpy/QuickWeb/sample/src/main/resources/quickweb.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="quickweb">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="session">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="charset"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="db">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="driver"/>
                            <xs:element name="url" type="xs:anyURI"/>
                            <xs:element name="username"/>
                            <xs:element name="password"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="view">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="prefix"/>
                            <xs:element name="suffix"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ffpy/QuickWeb/sample/src/main/resources/quickweb.xml
<?xml version="1.0" encoding="UTF-8" ?>
<quickweb xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="quickweb.xsd">
    <session>
        <charset>UTF-8</charset>
    </session>
    <db>
        <driver>com.mysql.jdbc.Driver</driver>
        <url>jdbc:mysql://localhost:3306/test?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false</url>
        <username>root</username>
        <password>123456</password>
    </db>
    <view>
        <prefix>/WEB-INF/views/</prefix>
        <suffix>.jsp</suffix>
    </view>
</quickweb>
